### ISSUE TITLE
No meta tags in the result xml

### ISSUE THREAD

**Issue by tan-feng** [AmerMathSoc/texml#197]
Are there any preconditions  mandatory for the input LaTex file? 
 I am running texml on my Ubuntu Linux 22.04,  it could ONLY convert 4 out of 8 articles successfully, with no errors reported.  Furthermore, no JATS meta tags injected in the result XML files.

**Comment by davidmjones** [comment]
Hi, Felix,

First, thanks for your interest.

> Are there any preconditions mandatory for the input LaTex file?

Yes, but I'm afraid they are ill-defined and undocumented at present.
This is something we hope to work on this year.  It's important to
realize that to date, `texml` has only been used internally at the
AMS, so it is targeted at documents using our own document classes and
the packages that we commonly encounter and allow.

One of our goals in making `texml` available is to gather information
about how the community would like to see it extended.  This would help us set priorities.

I've added some notes about this to the README under "Limitations."

> I am running texml on my Ubuntu Linux 22.04, it could ONLY convert 4
> out of 8 articles successfully, with no errors reported.

Can you share more information about your documents --- especially
what document classes and packages you are using --- and what went
wrong with the 4 papers that you couldn't convert?  To be honest, I'm
pleasantly surprised that you had a 50% success rate. :-)

> Furthermore, no JATS meta tags injected in the result XML files.

Currently metadata tags are only supported for `amsart` and `amsbook`;
and even if you use one of those classes, you will only get the meta
tags if you also have a `\maketitle` command in the document.  And, in
fact, at the AMS, most of the metadata is added by a private component
that pulls in the real metadata from an outside source since very
little is available in the LaTeX file.

**Comment by tan-feng** [comment]
Thanks for your quick response. After I changed the all the primitives of \documentclass{xxx} to \documentclass{amsart}, texml did generate meta tags  for me.  
It seems texml does pretty well for retrieval of titles and abstracts, hope it could do as well for meta  infos such as authors, keywords and thanks.
