### ISSUE TITLE
revisiting blockquotes

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/texml#32]
Issue https://github.com/AmerMathSoc/ams-html/issues/530 (triggered by mcom3395) led me to look at existing blockquotes in journal articles.

As of https://github.com/AmerMathSoc/ams-doc-sources/commit/91028f896934c776764aea188f145a6d71d1a606, we have 82 blockquotes across 24 articles, some of which seem a poor fit for the content. Let's review them in detail here.

* **btran15** 6 blockquotes 
  * 2 are actual quotes, 2 are actually attributions nested inside the two quotes
    * TeX source has flushright/flushleft for these 4
  * 2 are callouts, TeX has \begin{center}
* **btran18** 1 blockquote 
  *  a callout, TeX has \begin{quote}
* **btran25** 2 blockquotes
  * callouts in theorem statements; TeX has 2 \begin{quote}
* **btran29** 1 centered blockquote
  * around HTML table; TeX has \begin{center} 
* **btran31** 4 centered blockquotes 
  * 3 contain only an inline equation, i.e., they are faux display style equation
  * 1 is around a tikz
  * TeX has \begin{center}
* **jams421** 1 (empty) blockquote 
  * empty disp-quote; TeX has \begin{center} but its content is moved to a figcaption of an table (image)
* **jams895** 4 blockquotes
  * looks like recoded, complex numbered "equations" (minipage/parbox etc) - TeX has \begin{thingy} which has \quote
* **jams902** 8 centered blockquotes
  * all from \begin{center} around figures / images
  * 6 end up empty in mathviewer because the figure elements are moved to the figure panel
* **jams903** 1 centered blockquote
  * around image, TeX has begin{center} around tikz
* **mcom3323** 1 blockquote
  * a call out; TeX has \begin{quote}
* **mcom3334** 1 blockquote
  * a call out; TeX has \begin{quote}
* **mcom3335** 3 centered blockquotes 
  * around figures with tables; TeX has \begin{center}
* **mcom3338** 6 centered blockquotes
  * around images; TeX has \begin{center}
* **mcom3343** 1 centered blockquote
  * around figure with table (imag); TeX has \begin{center}
 * **mcom3351** 1 centered blockquote
   * around image of table; TeX has \begin{center}
* **mcom3352** 17 centered blockquotes
  * 14 are essentially headings; TeX has \begin{center}+bf
  * 3 faux display equations; TeX has \begin{center}
* **mcom3358** 1 centered blockquote
  * around a table (not a figure); TeX has \begin{center}
* **mcom3370** 10 centered blockquotes
  * each containing a single URL; TeX has \begin{center}
* **mcom3373** 2 centered blockquotes
  * each containing a single tt'ed word; TeX has \begin{center}
* **mcom3374** 6 centered blockquotes
  * all wrapping tables (without figure); TeX has \begin{center}
* **mcom3383** 1 blockquote 
  * looks like a recoded complex numbered equation; TeX has "thingy" environment
* **mcom3392** 1 blockquote
  * an actual quotation; TeX has `\begin{quote} {\it ...}`

# Resolved

* **bproc26** 1 centered blockquote
  * around an image of a table; TeX has \begin{center} (changed to figure)

# Accepted

* **bproc39** 2 blockquotes
  * both are callouts within theorem statements; TeX has \begin{quotation} (appropriate use)

(Note: mathviewer has 89 blockquotes because some are duplicated in secondary panels.)

**Comment by pkra** [comment]
bull1726 would also have greatly benefited since it was actually using quotations.

**Comment by davidmjones** [comment]
@pkra Following up on AmerMathSoc/gsm#22 after reviewing this issue again, I think I come down on the side of your suggestion of `boxed-text`:

> Textual material that is part of the body but is outside the flow of the narrative text (for example, a sidebar). 

> The [`<boxed-text>`](https://jats.nlm.nih.gov/archiving/tag-library/1.3/element/boxed-text.html) element can be used for any text insert whether enclosed in a box or not (for example, marginalia, sidebars, cautions, tips, warnings, note boxes).

If we ignore the "outside the flow of the narrative" bit, I can live with this.  Nothing really feels natural for all of the potential use cases, but I also doubt it's worth agonizing over this too much.

**Comment by davidmjones** [comment]
First, ignoring a few one-off uses, mostly in MCLs, here are the environments texml currently maps to `<disp-quote>`:
| LaTeX        | XML |
| ---------    | --- |
| `quotation`  | `<disp-quote content-type="quotation">` |
| `quote`      | `<disp-quote content-type="quote">` |
|            | 
| `epigraph`   | `<disp-quote content-type="epigraph">` |
|            | 
| `center`     | `<disp-quote specific-use="text-align: center">` |
| `flushright` | `<disp-quote specific-use="text-align: right">` |
| `flushleft`  | `<disp-quote specific-use="text-align: left">` |

Except for `epigraph`, these are all core LaTeX environments.

In case you're wondering,

> The quote environment is like the quotation environment except that paragraphs are not indented.

> The **quote** environment is used for either a short quotation or a sequence of short quotations separated by blank lines.

> The **quotation** environment is used for quotations of more than one paragraph; [...]

The JATS spec for `<disp-quote>` says

> Use this element for epigraphs, as well as for block quotes and extracts within text.

So I think all three of those are fine.

`center`, `flushright`, and `flushleft` are, of course, visual rather than semantic markup.  Most uses of `center` are already ignored by texml (inside figures, for example).  Remaining ones should mostly be replaced by anchored floats.  `flushright` and `flushleft` are very rare.  When they aren't just being used for something stupid (see mcom3698), `flushright` mostly seems to show up being used for some sort of epigraph, and `flushleft` is usually used just to suppress paragraph indentation.  I guess as a fall-back we could map them to `<boxed-text>` to keep them separate from quotations.

I'm ambivalent about distinguishing between true quotations and call-outs.  Even JATS endorses use of `<disp-quote>` for "extracts", which I think covers this use.

The purist in me agrees that having a separate element for them is the right thing to do; the pragmatist in me isn't sure this is the hill he wants to die on.  In practice, I'd have to introduce a new environment into the AMS document classes and then have TEG convert to that new coding during cleanup while maintaining the distinction between true quotations and call-outs.  It's doable, but is it really worth it?

**Comment by davidmjones** [comment]
Hmm.  Actually, I'm probably interpreting "extracts" too broadly.  Still, I just want this problem to go away.

**Comment by pkra** [comment]
The main problem, as I see it, is that that authors seem to misuse these environments *almost always*.

We also haven't really had a lot of complaints from QC regarding our current approach (only styling epigraph)

For journals, I can only recall a handful of papers where a proper quotation appeared.

I'm wondering if a pragmatic and purist approach might be to introduce new markup we can use to identify those few cases of actual quotations.

[For books, we can handle quotations either on the source level or via a publication-specific customization.]

**Comment by pkra** [comment]
As per F2F, we will effectively leave things as is in texml and adjust sources as needed.
